# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/MIPS_Processor/vivado_synthesis/MIPS_CPU/MIPS_CPU.cache/wt [current_project]
set_property parent.project_path C:/MIPS_Processor/vivado_synthesis/MIPS_CPU/MIPS_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib C:/MIPS_Processor/vivado_synthesis/MIPS_CPU/src/cpu.v
read_xdc {{C:/Users/reggert/Box Sync/Olin/Year IV/CompArch/support/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/reggert/Box Sync/Olin/Year IV/CompArch/support/ZYBO_Master.xdc}}]

synth_design -top cpu -part xc7z010clg400-1
write_checkpoint -noxdef cpu.dcp
catch { report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb }
